services:
  webserver:
    build:
      context: ./bin/${WEBSERVER}
    container_name: "${WEBSERVER}"
    restart: "on-failure"
    ports:
      - "${WEBSERVER_PORT}:80"
      - "${WEBSERVER_PORT_SSL}:443"
    links:
      - mysql
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR}:/var/log/apache2
  mysql:
    build:
      context: "./bin/${DATABASE}"
    container_name: "${DATABASE}"
    restart: "on-failure"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin"
    restart: "on-failure"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - /sessions
      - ${PHPMYADMIN_PHP_INI}:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
  redis:
    container_name: "redis"
    image: redis:latest
    restart: "on-failure"
    ports:
      - "${REDIS_PORT}:6379"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: "on-failure"
    environment:
      - REDIS_HOSTS=local:redis:${REDIS_PORT}
    ports:
      - "${REDIS_COMMANDER_PORT}:8081"
  fastapi:
    container_name: fastapi
    build: ./bin/api
    ports:
      - "8081:80"
    volumes:
      - ${FASTAPI_ROOT}:/code/app
